exclude: README.md|tests/.testlogs|.setuplog|tests

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8

- repo: https://github.com/ambv/black
  rev: 25.1.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
    - id: mypy
      args: [--exclude=site-packages, --python-version=3.10]

- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
    - id: interrogate
      args: [--fail-under=80, --verbose]
      additional_dependencies: [setuptools]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      args: ["--ignore=D107,D204,D407,D213,D212,D413,D406,D211, D203"]

- repo: local
  hooks:
    - id: set_hooks # This should match the script file name
      name: set-hooks
      entry: 'sh .set_hooks.sh'
      types: [bash]
      pass_filenames: false
      language: system
